version: '3.8'
services:
  mqtt-broker:
    container_name: mqtt-broker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./log:/application/log
    ports:
      - "1883:1883"
    restart: always